---
title: Presentación Instituto Peruano de Razonamiento Probatorio
author: ''
date: '2020-04-18'
slug: presentación-instituto-peruano-de-razonamiento-probatorio
categories:
  - Razonamiento probatorio
tags:
  - Teoría de la prueba
subtitle: ''
summary: ''
authors: []
lastmod: '2020-04-18T16:39:56-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

El pasado miércoles 15 de abril se llevó a cabo la presentación del [Instituto Peruano de Razonamiento Probatorio](http://iprp.pe/) conformado por Ricardo Elías, Juan Sánchez, Jesús Bautista, Raquel Limay y Rocío Rivera, exalumnos de la segunda generación del máster en razonamiento probatorio de la Universidad de Girona.

En el evento intervenimos Jordi Ferrer, Francisco Celis Mendoza, José Neyra y yo.

Tuve el honor de ser invitado para las palabras de clausura. Como señalé en esa oportunidad hay que felicitar la conformación del IPRP por cuanto pone en la escena nacional la importancia del razonamiento probatorio. Esa importancia, sin embargo, no debe centrarse solo en el derecho penal, sino que es necesario extenderlo en todas especialidades.

Otro aspecto que debe ser resaltado es que el estudio del razonamiento probatorio nos lleva a sorprendernos de que no existen certezas, ninguna, solo una alta probabilidad de que algo haya sucedido.

Un tercer aspecto que expuse es sobre el reto de la prueba y la justicia *online* más urgente que nunca en estos tiempo de distanciamiento social. Puede ser una oportunidad de simplificar para enfocarse en el tema de prueba, así como para incorporar las tecnologías y poner las ciencias a disposición de los jueces. Ese reto, sin embargo, pasa también por no descuidar el acceso a Internet, a la defensa. Retos que en un proyecto como el que inicia el IPRP puede ayudar a una mejor y mayor discusión y claridad sobre las decisiones de política jurisdiccional a tomar.

Puede ver mi participación a partir de la hora y 12 minutos.

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode("youtube", "Lwj2gCiZQIw")
```
