---
title: 'R. M. 239-2020-MINSA (ACTUALIZADA CON R.M. 265-2020-MINSA): lineamientos para
  la vigilancia, prevención y control de la salud de los trabajadores con riesgo de
  exposición a COVID-19'
author: PaulParedes
date: '9 de mayo de 2020'
categories:
  - Derecho individual del trabajo
tags:
  - Coronavirus
  - Derecho del trabajo
  - Estado de emergencia
slug: r-m-239-2020-minsa-pautas-básicas-de-protección-de-la-salud-de-los-trabajadores
lastmod: '2020-05-09T16:04:52-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
output: pdf_document
fontsize: 12pt
---

Versión PDF [AQUÍ](/pdf/r-m-239-2020-minsa-pautas-basicas-de-proteccion-de-la-salud-de-los-trabajadores.pdf) 

## Criterios generales 

- Esta normas tiene como propósito establecer pautas generales, a nivel nacional, aplicable **a todos los trabajadores y todos los empleadores, cualquiera sea la actividad realizada, tanto ser sector público como privado**, incluidos los miembros de las Fuerzas Armadas y Policía Nacional.

  - Estos lineamientos --de vigilancia, prevención y control de la salud-- se aplican a los trabajadores que realizan actividades durante la pandemia.

  - También aplica a quienes vayan regresando a trabajar, según el cronograma que apruebe el gobierno.

- Estas son **pautas mínimas** que deben ser seguidas por todos los empleadores, **cualquiera sea el sector productivo al que pertenezca**.

## El "Plan para la vigilancia, prevención y control del COVID-19 en el trabajo"

- Es el "documento que contiene las medidas que se deberán tomar para vigilar el riesgo de exposición a COVID-19 en el lugar de trabajo". Debe incluir las medidas respecto a practicantes, visitas o proveedores.

- Tienes que ser aprobado antes del reinicio de las actividades.

- El plan recoge los lineamientos de la R. M. 239-2020-MINSA aplicados a cada centro de trabajo.

- El plan puede establecer mayores medidas de prevención según la actividad económica, los puestos del centro de  trabajo, el riesgo de exposición a COVID-19.

- El plan puede contener otros lineamientos específicos para COVID-19, pero, en adición a los de la R.M. 239-2020-MINSA; es decir, los posibles otros lineamiento nunca podrían ponerse en sustitución de la R.M. 239-2020-MINSA.

- El plan debe considerar medidas de salud mental.

- El plan forma parte del Sistema de Gestión de Seguridad y Salud en el Trabajo.

## Aprobación del plan

- El empleador a través del servicio de seguridad y salud en el trabajo elabora el plan.

- El plan es remitido al Comité --o al Supervisor-- de Seguridad y Salud en el Trabajo, según corresponda, para su aprobación en el plazo máximo de 48 horas.

- El plan debe ser registrado en el Instituto Nacional de Salud a través del Sistema Integrado para COVID-19 (SICOVID-19) de modo virtual.

- Estos planes serán accesibles a las entidades de fiscalización como SUNAFIL, SUSALUD, entre otras.

## Los 7 lineamientos para la vigilancia, prevención y control de COVID-19 en el trabajo

### 1. Limpieza y desinfección de los centros de trabajo

- Limpieza y desinfección de todos los ambientes de trabajo, previo al inicio de labores diarias:
  - Ambientes
  - Mobiliario
  - Herramientas
  - Equipos
  - Útiles de escritorio
  - Vehículos

### 2. Evaluación de la condición de salud del trabajador previo al regreso o reincorporación al centro de trabajo

- Esta labor está a cargo de un profesional de la salud de cada centro de trabajo

- Su labor consiste en:

  - Identificar los riesgos de exposición COVID de cada puesto de trabajo.
  
  - Los trabajadores deben completar la Ficha de Sintomatología COVID-19 y se la entrega al empleador (según R.M. 265-2020-MINSA) ~~Aplicación a cada trabajador, al momento del retorno, de la Ficha de Sintomatología, la cual tiene carácter declarativo~~.
  
  - Control de temperatura corporal al ingreso al centro de trabajo.
  
  - Aplicación de pruebas serológicas o molecular en el caso que los puestos sean de Muy Alto, Alto y Mediano riesgo.
  
  - Corresponde al profesional de la salud determinar si el trabajador puede retornar a su puesto de trabajo.

  - La periodicidad de las pruebas debe estar contenida en el Plan.
  
  - Los costos de la evaluación son de cargo del empleador.

#### Caso de bajo riesgo
  
  - Si el puesto de trabajo es de Bajo riesgo, la aplicación de las pruebas queda sujeta a la decisión del profesional de la salud.
  
  - En este último caso, sin embargo, si resulta un caso sospechoso:
  
    - Se aplica la Ficha Epidemiológica COVID-19
    - Se aplica la prueba serológica o molecular
    - Se identifican los contactos que tuvo el paciente
    - Se hace seguimiento clínico a distancia diario
    - Debe cumplir 14 días de aislamiento, luego de los cuales el profesional de la salud realiza la evaluación clínica para determinar su retorno al trabajo
  
### 3. Lavado y desinfección de manos (puntos importantes)

- Se establecen puntos de lavado de manos de uso libre.

- Uno de los puntos de lavado o alcohol gel se ubica al ingreso del centro de trabajo.

- Mediante un cartel, en el punto de lavado, se indica el correcto modo de lavarse las manos.
 
### 4. Sensibilización de la prevención del contagio en el centro de trabajo (puntos importantes)

- Información sobre el coronavirus.

- Importancia del lavado de manos.

- Uso de mascarillas obligatorio durante la jornada.

- Educación en prevención.

### 5. Medidas preventivas de aplicación colectiva (puntos importantes)

- Ambientes ventilados.

- Distanciamiento social de un (1) metro entre trabajadores, incluso en comedores, ascensores, etc.

- Uso permanente de mascarilla.

- Reuniones de trabajo preferentemente virtuales.

- Uso de barreras físicas en el caso de personal de atención al público.

- Limpieza y desinfección de calzado antes de ingresar a áreas comunes en el centro de trabajo.

- Evitar aglomeraciones al ingreso y salida del centro de trabajo.

### 6. Medidas de protección personal

- El empleador debe asegurar la disponibilidad de los equipos de protección personal como, por ejemplo, las mascarillas o respiradores.

### 7. Vigilancia de la salud del trabajador en el contexto del COVID-19

- Control de temperatura corporal de los trabajadores al ingreso y al finalizar la jornada.

- Se identifican los casos sospechosos, a los cuales se aplica la ficha epidemiológica, las pruebas serológicas o moleculares, identificación de contactos, aplicación de pruebas a los contactos.

- Identificación de factores de riesgo ergonómicos, psicosociales y otros como consecuencia de trabajar en el contexto de la pandemia.

- El Plan debe considerar medidas de salud mental.

- Se debe proteger a los trabajadores que tengan alguna **discapacidad**. Al respecto, conforme al artículo 4.7 del Decreto Legislativo 1468 (23/04/2020): *"En caso la naturaleza de las labores del puesto de trabajo no sea compatible con el trabajo remoto o a falta de acuerdo, corresponde otorgar una licencia remunerada con cargo a compensación al culminar la emergencia sanitaria ocasionada por el COVID-19"*. 

- En caso de brote de COVID-19 se comunica inmediatamente a la SUNAFIL para el cierre y paralización inmediata de labores.

- Cuando los empleadores realizan directamente el tamizaje para COVID-19 deben solicitar a la DIRIS, DISA, DIRESA O GERESA formar parte de la Red Nacional de Epidemiología en calidad de unidad informante o unidad notificante (agregado por la R.M. 265-2020-MINSA).

- El seguimiento de contactos será realizado por el personal de la salud del Servicio de Seguridad y Salud en el Trabajo del empleador, en coordinación con las DIRIS, DISA, DIRESA o GERESA (agregado por la R.M. 265-2020-MINSA).

- El primer día de seguimiento se realiza mediante visita domiciliaria y los siguientes (hasta completar 14) se puede realizar por llamadas telefónicas (agregado por la R.M. 265-2020-MINSA).

## Diferencia entre "regreso" y "reincorporación" al trabajo en la R.M. 239-2020-MINSA

- **Regreso al trabajo** aplica a los trabajadores que han cumplido la cuarentena en sus domicilios sin presentar síntomas COVID-19 ni ser sospechosos o positivos a COVID-19, cuyo centro de trabajo no ha continuado laborando desde el Estado de Emergencia Nacional.

- **Reincorporación al trabajo** aplica a los trabajadores que tienen alta epidemiológica COVID-19. 

  - Si el caso fue leve, la reincorporación se da 14 días después del aislamiento.
  
  - Si el caso fue moderado o severo, la reincorporación se da 14 días después del alta clínica.
  
## Trabajadores que retornan cuyas actividades son actividades de riesgo diferentes al COVID

- El empleador debe brindarles una revisión, actualización o reforzamiento de los procedimientos técnicos.

- Esta actualización puede ser virtual o presencial, según corresponda.

## Trabajadores con factores de riesgo

- Estos trabajadores deben mantener la cuarentena hasta que lo disponga el gobierno.

- El profesional de la salud determina su regreso o reincorporación al trabajo.

### Los factores de riesgo son (actualizado con la R.M. 265-2020-MINSA):

- Edad mayor de 60 años

- Hipertensión arterial

- Enfermedades cardiovasculares

- Cáncer

- Diabetes mellitus

- Obesidad con IMC de 40 a más ~~30 a más~~

- Asma

- Enfermedad pulmonar crónica ~~respiratoria crónica~~

- Insuficiencia renal crónica

- Enfermedad o tratamiento inmunosupresor

- Según las R.M. 239 y 265-2020-MINSA el médico podría considerar algún otro caso en este grupo

- Los trabajadores comprendidos en este grupo mantienen la cuarentena hasta el término de la emergencia sanitaria (según la R.M. 265-2020-MINSA)

*** 



