---
title: 'D.S. 010-2020-TR: trabajo remoto, infracciones al estado de emergencia y fiscalización
  laboral'
author: 'Paul Paredes'
date: '2020-03-24'
output: pdf_document
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2020-03-24T20:16:44-05:00'
categories: 
   - Derecho individual del trabajo
projects: []
slug: d-s-010-2020-tr-trabajo-remoto-infracciones-al-estado-de-emergencia-y-fiscalización-laboral
subtitle: ''
summary: ''
tags:
  - Coronavirus
  - Derecho del trabajo
  - Suspensión
  - Trabajo remoto
  - SUNAFIL
authors: []
---
Descargue la versión del artículo en pdf [AQUÍ](/files/ds010-2020-tr.pdf) 

D.S. 010-2020-TR, "que desarrolla disposiciones para el sector privado, sobre el trabajo remoto previsto en el D.U. 026-2020".

Texto publicado del martes 24 de marzo de 2020. 

## Precisiones respecto del trabajo remoto

  1. El empleador debe comunicar a sus trabajadores la implementación del trabajo remoto, a quienes corresponda. De ello debe dejarse constancia por cualquier medio.
  2. Un punto importante en dicha comunicación es que debe contener las condiciones de seguridad y salud en el trabajo aplicables.
  3. El trabajar que esté con descanso médico debe comunicarlo a su empleador así como la conclusión del mismo para recibir las instrucciones sobre el trabajo remoto, en caso corresponda.
  4. Cuando los medios para prestar el trabajo remoto sean proporcionados por el trabajador, se puede acordar la compensación de los gastos adicionales derivados de su uso.
  5. Las partes pueden pactar la distribución de la jornada de trabajo en los horarios que mejor se adapten a sus necesidades, respetanto los máximos de 8 horas diarias y 48 horas semanales.
  6. El trabajador "remoto" debe estar disponible durante la jornada de trabajo.
  7. Se precisa que las reglas del trabajo remoto también aplican a quienes se encuentran bajo modalidad formativa, en tanto sea compatible con el tipo de modalidad formativa empleada.
  
## Medidas adicionales

### Fiscalización laboral

Se señala que la inspección del trabajo cumplirá sus funciones durante el estado de emergencia "para cautelar los derechos de los trabajadores".

### Infracción muy grave en el marco del estado de emergencia

Se establece como **infracciones muy graves**, las siguientes:

a) Disponer, exigir o permitir el **ingreso** o la **permanencia** de personas:
  
   1. Para prestar servicios en los centros de trabajo **cuya actividad no se encuentre exceptuada del estado de emergencia**; o,
   2. Para **labores que no sean las estrictamente necesarias** dentro del ámbito de la excepción.
  
b) Incumplir con la regulación aplicable al **trabajo remoto** para los trabajadores considerados en el **grupo de riesgo** por los periodos de emergencia nacional y sanitaria.
  

## Vigencia de las medidas

Rige por el periodo que dure la emergencia sanitaria.

## Aplicación supletoria

La norma es de aplicación supletoria para los trabajadores del sector público en lo que corresponda.
