---
title: 'D.S. 011-2020-TR: reglamento del D.U. 038-2020 sobre suspensión perfecta'
author: 'Paul Paredes'
date: '21 de abril de 2020'
output: pdf_document
featured: no
fontsize: 12pt
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2020-04-21T19:10:03-05:00'
categories:
  - Derecho individual del trabajo
  - Procedimientos administrativos
projects: []
slug: d-s-011-2020-tr-reglamento-del-d-u-038-2020-sobre-suspensión-perfecta
subtitle: Publicado en El Peruano el martes 21 de abril de 2020
summary: ''
tags:
  - Coronavirus
  - Derecho del trabajo
  - Estado de emergencia
  - SUNAFIL
  - Suspensión
  - Teletrabajo
  - Trabajo remoto
authors: []
---

Versión en PDF del artículo [AQUÍ](/files/2020-04-21-d-s-011-2020-tr-reglamento-del-d-u-038-2020-sobre-suspensión-perfecta.pdf) 

## La regulación de la suspensión perfecta en el D.U. 038-2020 y el D.S. 011-2020-TR

En una anterior publicación hice un resumen del D.U. 038-2020 que reguló la **suspensión perfecta** la labores. El pasado 21 de abril se ha publicado el D.S. 011-2020-TR que la reglamenta, por lo que, en esta ocasión, haré un resumen de ambas normas centrándome en la suspensión perfecta, a fin de anotar sus características más importantes. En paréntesis se indica el número del artículo del D.U. 038.

## 1. ¿A qué trabajadores se les podría aplicar las medidas del DU 038?
- A los trabajadores del sector privado (2).
- A los trabajadores de FONAFE (5 DCF).
- A los trabajadores de las empresas del Estado (5 DCF).
- El reglamento (art. 2) refuerza esta idea: aplica a todo el sector privado bajo cualquier régimen laboral.
  
## 2. ¿Qué grupo de empleadores puede aplicar estas medidas? (3.1)
1. Los que no pueden implementar el trabajo remoto por la naturaleza de sus actividades. 
    - Porque es imposible su aplicación (es indispensable la presencia física del trabajador)
   
2. Los que no pueden aplicar la licencia con goce de haber *por la naturaleza de las actividades*.
    - Cuando no es razonable la compensación del tiempo dejado de laborar en atención a causas objetivas vinculadas con la prestación:
      - los turnos cubren las 24 horas del día
      - naturaleza riesgosa de las actividades por la extensión del horario
      - horario de atención sujeto a restricciones legales
      - otras situaciones que escapen al control de las partes
    
    * Esta causal es muy discutible y parece inventada para habilitar más supuestos de suspensión. ¿Hay algún caso donde no se pueda compensar con posterioridad? 

3. Los que tienen un nivel de afectación económica a la fecha de entrada en vigencia del D.U. (15 de abril de 2020).
    - El reglamento dice que esto sucede cuando se da una situación económica que les impide severa y objetivamente aplicar dichas medidas (la licencia con goce de haber).

## 2.1. El nivel de afectación económica (para la suspensión perfecta)

- El D.U. no define qué significa "nivel de afectación económica". El D.S. sí lo hace y establece un número de **puntos de diferencia** a partir de los cuales se cumpliría la condición de la afectación económica.
  
- La idea central de esta diferencia es la siguiente:
    - Por ejemplo, si la suspensión se da en abril 2020
    - **A** menos **B** = un número de puntos.
    - Donde **A** se obtiene de dividir [Suma de remuneraciones trabajadores declarados en planilla mes Marzo 2020] entre [Suma ventas del mes de marzo 2020]
    - Donde **B** se obtiene de dividir [Suma de remuneraciones trabajadores declarados en planilla mes Marzo 2019] entre [Suma ventas del mes de marzo 2019]
    - Entonces: **A menos B = X puntos**.
    - Ese valor se compara con el valor de la tabla y se verifica si cumple o no cumple el nivel de afectación económica.

### Tabla si suspensión en abril 2020
   
|Actividades | Tamaño empresa | Puntos de diferencia | Resultado |
|------|-------|:------:|:--------:|
|Actividades permitidas | Micro y pequeña empresa | > 6 | Sí |
|Actividades permitidas | Micro y pequeña empresa | <= 6 | No |
|Actividades permitidas | Mediana y gran empresa | > 13 | Sí |
|Actividades permitidas | Mediana y gran empresa | <= 13 | No |
|Actividades no permitidas | Micro y pequeña empresa | > 4 | Sí |
|Actividades no permitidas | Micro y pequeña empresa | <= 4 | No |
|Actividades no permitidas | Mediana y gran empresa | > 11 | Sí |
|Actividades no permitidas | Mediana y gran empresa | <= 11 | No |

### Tabla si suspensión en mayo 2020 o posterior
   
|Actividades | Tamaño empresa | Puntos de diferencia | Resultado |
|------|-------|:------:|:--------:|
|Actividades permitidas | Micro y pequeña empresa | > 12 | Sí |
|Actividades permitidas | Micro y pequeña empresa | <= 12 | No |
|Actividades permitidas | Mediana y gran empresa | > 26 | Sí |
|Actividades permitidas | Mediana y gran empresa | <= 26 | No |
|Actividades no permitidas | Micro y pequeña empresa | > 8 | Sí |
|Actividades no permitidas | Micro y pequeña empresa | <= 8 | No |
|Actividades no permitidas | Mediana y gran empresa | > 22 | Sí |
|Actividades no permitidas | Mediana y gran empresa | <= 22 | No |

### Importante
Si en el caso de que las ventas del mes previo a la adopción de la medida correspondiente sea igual a cero, el empleador sí puede aplicar la suspensión.
    - Pero siempre debe evaluarse si, previamente, cumplió con la negociación previa.

      
## 3. ¿Qué medidas son estas? (3.1)
- "Las medidas que **resulten necesarias** a fin de mantener la vigencia del vínculo laboral y la percepción de remuneraciones".
- Hasta aquí, cualquiera de esas medidas excluiría a la suspensión perfecta porque este no cumple la finalidad de "la percepción de remuneraciones".
- La sorpresa viene pues con la ya famosa **suspensión perfecta**.
    
## 4. ¿Qué condición debe cumplirse para adoptar las medidas? (3.1)
- MUY IMPORTANTE: se privilegia el acuerdo con los trabajadores.
- Esto merece atención:
- ¿Qué es privilegiar el acuerdo?
- Los trabajadores y sindicatos deberían exigir se les haga participar en la toma de acuerdos.
- No hay garantías para un libre acuerdo (informado y de buena fe) por lo que será muy fácil que se imponga la voluntad del empleador.
- Si hay una simple imposición se estaría vulnerando la exigencia del acuerdo.
      
## 5. La suspensión perfecta de labores (3.2)
- Suspensión perfecta de labores es: trabajador no labora y empleador no paga remuneraciones. Es lo contrario a la finalidad del artículo 3.1 que, se supone, es mantener la percepción de la remuneración.
- Es excepcional. 
- Si es excepcional es porque debe haberse agotado alguna negociación con los trabajadores o sindicato.
- No podría ser la primera medida a ser adoptada porque,entonces, no sería excepcional.
- Debe exponer los motivos que la sustenta. De ahí la importancia de lo dicho en el punto 4.
- En el caso de utilizarse **el nivel de afectación económica** esta debería demostrarse por el empleador en el momento de la negociación con documentos oficiales:
    - Declaración jurada Formulario 621, casilla 301.
    - Registro de ventas
    - Formulario PDT 601 Planilla Electrónica PLAME

## 6. Procedimiento de la suspensión perfecta (3.2, 3.3, 3 DCF)

- Empleador envía por correo una comunicación (con calidad de declaración jurada) a la Autoridad Administrativa de Trabajo (AAT).
- En esa comunicación expone los motivos que la sustentan (ver punto 4).
- Esa comunicación está sujeta a verificación posterior a cargo de la Inspección en un plazo no mayor de 30 días hábiles de presentada la comunicación.
- La AAT expide resolución (convalidando la medida o no) dentro de los 7 días hábiles siguientes de la Inspección de verificación. 
    - Si no se expide la resolución se entiende APROBADA la suspensión perfecta.
    - La norma no lo dice pero contra dicha resolución, expresa o ficta, caben interponer los recursos de impugnación correspondiente, salvo en los casos donde la Dirección General de Trabajo actúa como instancia única. Puede verse al respecto, el D.S. 017-2012-TR.
    - No menos importante es advertir que, en estos casos, no opera la suspensión de plazos por lo que hay necesidad de estar atentos y defenderse a pesar de la inamovilidad social. (3 DCF)
- **IMPORTANTE**: Se debe verificar si el empleador procuró la adopcioń de medidas para mantener la vigencia del vínculo laboral y la percepción de las remuneraciones, privilegiando el acuerdo entre los trabajadores.
- **IMPORTANTE**: La adecuación de las comunicaciones de suspensión previas al D.S. 011-2020-TR no puede significar que los empleadores cumplan recién los requisitos, sino solo que presenten los documentos que dan sustento a su decisión tomada. En ese sentido, NO SE DEBE PERMITIR QUE EL EMPLEADOR INTENTE ACUERDOS O SUPUESTAS NEGOCIACIONES SOLO PARA CONVALIDAR REQUISITOS, PUES EL INCUMPLIMIENTO DE LA NEGOCIACIÓN HABRÍA OCURRIDO Y NO SE PUEDE SUBSANAR DESPUÉS. ELLO CONFIRMARÍA QUE EL EMPLEADOR TOMÓ LA DECISIÓN SIN HABERTE INTENTADO ACUERDOS CON LOS TRABAJADORES O SINDICATO.
    
### 6.1 Reglas de notificación de los distintos procedimientos administrativos relativos a las relaciones laborales (2 DCF)
- Durante el Estado de Emergencia Sanitaria las notificaciones de los actos administrativos y otros se realizan por correo electrónico u otro medio digital.
- En las primeras comunicaciones a la AAT debe indicarse una dirección electrónica para las notificaciones.
- La notificación dirigida al correo electrónico indicado se entiende válidamente efectuada.
- La notificación surte efecto el día que conste haber sido recibida
- La disponibilidad y funcionamiento del correo electrónico es responsabilidad de los administrados.

## 7. ¿En qué casos no debería aprobarse la suspensión perfecta? (3.4)
- Cuando haya falta de correspondencia entre la comunicación presentada y la verificación realizada por la Inspección.
- Cuando haya afectación a la libertad sindical.
- También debería no ser aprobada cuando el empleador no haya acreditado que haya negociado previamente con los trabajadores o sindicato. Esto sería así por cuanto se supone que la suspensión perfecta es excepcional y que el principal propósito del DU es mantener la percepción de las remuneraciones.

## 8. Vigencia de las medidas, incluida la suspensión perfecta de labores (3.5)
- "Hasta 30 días calendario luego de terminada la vigencia de la Emergencia Sanitaria".
    - La Emergencia Sanitaria viene en el D.S. 008-2020-SA, publica el 11 de marzo de 2020 y vigente desde el 12.
    - Esta norma declaró la Emergencia Sanitaria por el plazo de 90 días a nivel nacional, es decir, del 12 de marzo al 9 de junio de 2020.
    - En otras palabras, las medidas del DU podrían tener una vigencia hasta 30 días calendario después del 9 de junio, es decir, hasta el 9 de julio de 2020. ¡Más de los 90 días del D.S. 003-97-TR!
    - Pero, adicionalmente, este plazo podría ser prorrogado por decreto supremo de los ministerios de Trabajo y Economía y Finanzas.
    - Esto genera un problema:
    - El sustento de todas estas medidas es la situación excepcional del caso fortuito y la fuerza mayor.
    - Pero una medida mayor a los 90 días pone en discusión que se trate ya de una situación excepcional y más bien empieza a parecer más a un cambio de las reglas laborales.
        
## 9. Situación de los trabajadores del grupo de riesgo por edad o factores clínicos (4)
- El D.U. 026-2020 estableció que, en el caso de los trabajadores del grupo de riesgo que no pudiesen cumplir con el trabajo remoto, debía concedérseles licencia con goce de haber compensable con posterioridad.
- El D.U. 038-2020 señala que cuando ya no sea posible otorgarles la licencia con goce compensable, los empleadores pueden adoptar las medidas que resulten necesarias a fin de mantener el vínculo laboral y la percepción de remuneraciones, privilegiando el acuerdo con los trabajadores.
- Esta disposición es un tanto confusa porque terminaría reconociendo lo que ya existe, en tanto la medida para mantener el vínculo y la percepción de las remuneraciones es, precisamente, la licencia con goce de haber.
- Al abrir lo de "privilegiar el acuerdo" se estaría permitiendo la imposición de la voluntad del empleador bajo la apariencia de un acuerdo.
    
## 10. Otras medidas laborales (4 DCF)
- Por si esto parece poco se agrega que "el empleador puede adoptar las medidas establecidas en el marco laboral vigente.
- La gran pregunta es: ¿ello incluiría los procedimientos de cese colectivo?
- En todo caso, no hay que olvidar que los derechos de negociación colectiva y libertad sindical no están suprimidos por lo que la AAT deberá tomarlos en consideración al momento de resolver los distintos procedimientos.
    
## 11. Listado de las otras medidas contenidas en el D.U. 038-2020 (5, 6, 7, 8, 9, 10)

En esta parte solo haré mención a las otras medidas que aparecen en el D.U. que tienen un sentido más económico y que, sin duda, daría pie a otras reflexiones que podría desarrollarse más adelante.

Estas medidas para los trabajadores o ex trabajadores son:

  1. Continuidad de las prestaciones de salud para los trabajadores que pasen a suspensión perfecta, por el tiempo de duración de la suspensioń.
  2. A los trabajadores en suspensión perfecta, disponer libremente de su cuenta CTS hasta una remuneración bruta mensual por cada mes calendario vencido de duración de la suspensión.
  3. A los trabajadores en suspensión perfecta, que no tengan saldo en su cuenta CTS, pueden pedir al empleador el adelanto de pago de la CTS de mayo 2020 y de la gratificación de julio 2020.
  4. A los trabajadores en suspensión perfecta del régimen de las microempresas, cuya remuneración mensual bruta no supere los S/2,400.00 se les comprende en el programa "Prestación Económica de Protección Social de Emergencia ante la Pandemia del Coronavirus COVID-19".
    - Esta medida consiste en que el Seguro Social pague a esos trabajadores hasta S/760.00 por cada mes calendario vencido que dure la suspensión, pero hasta un límite de 3 meses.
  5. A los trabajadores en suspensión perfecta que hubiesen alcanzado en ese periodo los aportes necesarios para acceder a una pensión, no se les exigirá los aportes del periodo de suspensión, pudiendo la ONP reconocerles hasta 3 meses de aportes.
  6. A los trabajadores en suspensión perfecta, se les permitirá, por única vez, retirar hasta S/2,000.00 de la cuenta individual en la AFP.
  7. A quienes no cuenten con acreditación del aporte previsional obligatorio, de febrero o marzo 2020, pueden retirar, por única vez, hasta S/2,000.00.
  8. A quienes sí cuentan con acreditación del aportes previsional obligatorio de febrero o marzo 2020, y cuya última remuneración declarada sea menor o igual a S/2,400.00.
  
Para los empleadores, se ha considerado las siguientes medidas: (11)

1. Puede aplazar el depósito CTS de mayo 2020 hasta noviembre 2020 considerando los intereses devengados.
2. Esta regla no aplica, y por tanto, debe depositar la CTS en mayo, en los siguientes casos:
    - La remuneración bruta del trabajador sea de hasta S/2,400.00; o,
    - Los trabajadores estén en suspensión perfecta de labores.

## 12. Comentarios adicionales

1. Debe tenerse presente que la posibilidad de la suspensión perfecta --con las condiciones señaladas-- no es retroactiva:
    - Del 16 de marzo hasta el 14 de abril, aplica el artículo 26° del D.U. 029-2020 que dispuso la licencia con goce de haber compensable.
    
2. Los trabajadores y sindicatos pueden participar en estos procedimientos y hacer escuchar su voz, sobre todo para evidenciar si hubo o no un acercamiento y negociación con el empleador.
3. Puede servir de criterio para cuestionar el nivel de afectación económica, además de lo expuesto, entre otros, los siguientes casos:
    - Empresas que han repartido utilidades.
    - Empresas que cotizan en bolsa.
    - Empresas que han ofrecido préstamos a sus trabajadores.

*** 


